### ISSUE TITLE
**Processing Workplan**

### ISSUE THREAD

**Issue by maryhaberle** [MKFA/archives#1]
- [ ] Prioritize series for processing
- [ ] Describe processing levels per series
- [ ] Define preservation actions to be taken at each level
